name: symbolic_mbrl
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==23.1.2
  - python==3.10.2
  - pip:
    - mbrl
    - torch
    - pygame==2.6.0
    - numpy==1.24
    - pyoperon
    - scikit-learn